import { Metadata } from 'next';
import InsightCards from '../components/InsightCards';

export const metadata: Metadata = {
  title: 'Insights - Green Blockchain Monitor',
  description: 'AI-generated insights and recommendations for blockchain sustainability',
};

export default function InsightsPage() {
  return (
    <div className="space-y-8">
      <div className="bg-white rounded-lg shadow-md p-6">
        <h1 className="text-2xl font-bold text-gray-900 mb-4">
          AI-Powered Insights
        </h1>
        <p className="text-gray-600 mb-6">
          Discover actionable insights and recommendations generated by our AI system.
          These insights are based on real-time data analysis and historical trends.
        </p>
      </div>

      {/* Insights Cards */}
      <InsightCards />
    </div>
  );
} 